name: speak_nato
description: Multi-language phonetic alphabet.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  flushbar:
  flutter_tts:
  shared_preferences: ^0.4.0
  card_settings:

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  fonts:
    - family: Helvetica
      fonts:
        - asset: fonts/Helvetica.ttf
        - asset: fonts/Helvetica-Bold.ttf
